{{- range $key, $value := .Values.issuersMap }}
---
apiVersion: cert-manager.io/v1
kind: {{ $value.kind }}
metadata:
  name: {{ $key }}
  {{- if $value.namespace }}
  namespace: {{ $value.namespace }}
  {{- end }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
    {{- if $value.labels }}
    {{- toYaml $value.labels | trim | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "app.annotations" $ | nindent 4 }}
    {{- if $value.annotations }}
    {{- toYaml $value.annotations | trim | nindent 4 }}
    {{- end }}
spec:
  {{- toYaml $value.spec | trim | nindent 2 }}
{{- end }}
