---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.envSecrets }}
  {{ $key | lower | replace "_" "-" }}: {{ $value | b64enc | quote }}
  {{- end }}
