---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
# deploymentSpec
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "app.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.labels" . | nindent 8 }}
      annotations:
        {{- include "app.annotations" . | nindent 8 }}
    # podSpec
    spec:
      # podSpec
      containers:
      # containerSpec
      - name: {{ include "app.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        env:
        # envSecrets
        {{- range $key, $value := .Values.envSecrets }}
        - name: {{ $key | quote }}
          valueFrom:
            secretKeyRef:
              name: {{ include "app.fullname" $ }}
              key: {{ $key | lower | replace "_" "-" }}
        {{- end }}
        # env
        {{- range $key, $value := .Values.env }}
        - name: {{ $key | quote }}
          value: {{ $value | quote }}
        {{- end }}
        # extraContainerSpec
        {{- if .Values.extraContainerSpec }}
        {{- toYaml .Values.extraContainerSpec| trim | nindent 8}}
        {{- end }}
      # extraPodSpec
      {{- if .Values.extraPodSpec }}
      {{- toYaml .Values.extraPodSpec| trim | nindent 6 }}
      {{- end }}
  # extraDeploymentSpec
  {{- if .Values.extraDeploymentSpec }}
  {{- toYaml .Values.extraDeploymentSpec | trim | nindent 2 }}
  {{- end }}
