{{- if .Values.pvc.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  {{- if .Values.pvc.spec }}
  {{- toYaml .Values.pvc.spec | trim | nindent 2 }}
  {{- end }}
{{- end }}
