name: Helm Chart Release

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-22.04
    container:
      image: quay.io/helmpack/chart-releaser:v1.6.0
      options: --user 1001
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup git user
      run: |
          git config --global user.name "zzamzam"
          git config --global user.email "dangeron@gmail.com"

    - name: Package charts
      run: ls -d */ | xargs cr package

    - name: Upload charts
      run: >-
        cr upload
        --owner zzamtools
        --git-repo helm-charts
        --packages-with-index
        --token '${{ secrets.GITHUB_TOKEN }}'
        --pages-branch gh-pages
        --push
        --skip-existing

    - name: Upload index
      run: >-
        cr index
        --owner zzamtools
        --git-repo helm-charts
        --packages-with-index
        --index-path .
        --token '${{ secrets.GITHUB_TOKEN }}'
        --pages-branch gh-pages
        --push
